Agalles/bwwl actionlint
bitwarden/workflow-linter pull request #39
Opened 2024-12-27 16:55 UTC by AmyLGalles

## 🎟️ Tracking

From [BRE-469](https://bitwarden.atlassian.net/browse/BRE-469)

## 📔 Objective

Workflow Linter V2 is meant to run alongside Actionlint, so it makes sure to run Actionlint as a part of the default workflow linter run.

Enabled for Workflow-linter workflows only so far.  Other repositories with settings override will need the job added to their settings.yaml file

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-12-31 11:03 UTC, Eeebru approved these changes

2025-01-06 14:39 UTC, Eeebru commented
The test coverage needs to be improved on, for example we can test for:

1. When filename is not passed (line 75-76)
2. When action lint fails for some reason and returns higher error code (line 89)
3. When we have an install error (line 92-93)

We want to strive for 100% coverage for the rules in `src/bitwarden_workflow_linter/rules` directory, there the ones we really can test succinctly. 

We have this in the `README:` 

"All built-in `src/bitwarden_workflow_linter/rules` should have 100% code coverage and we should shoot for an overall coverage of 80%+. We are lax on the [imperative shell](https://www.destroyallsoftware.com/screencasts/catalog/functional-core-imperative-shell) (code interacting with other systems; ie. disk, network, etc), but we strive to maintain a high coverage over the functional core (objects and models)."

2025-01-06 14:46 UTC, Eeebru requested changes

2025-01-06 14:46 UTC, Eeebru commented on tests/rules/test_run_actionlint.py
> +    result, _ = rule.fn(incorrect_workflow)
This test is also going to return `true`, because there is nothing failing the passed-in workflow. You might need to create a dummy workflow that will fail `actionlint` within this test file to get a `false` result.

2025-01-06 15:03 UTC, Eeebru commented
The CI is failing because it can't install `actionlint`

2025-01-13 15:50 UTC, michalchecinski reviewed
Great work! It looks good to me. A small suggestion from me would be to add a prerequisite in the README that a package manager (`brew` for macOS and `chocolatey` for Windows ) is needed to run the project.

2025-01-13 15:53 UTC, mimartin12 commented on src/bitwarden_workflow_linter/rules/run_actionlint.py
> +    version = "1.6.17"
❓ Is this the best place to store the version of actionlint today?

2025-01-13 15:55 UTC, michalchecinski commented on src/bitwarden_workflow_linter/rules/run_actionlint.py
> +    version = "1.6.17"
Also, is it possible to use Renovate to automate the actionlint version updates here?

2025-01-13 16:01 UTC, mimartin12 commented on src/bitwarden_workflow_linter/rules/run_actionlint.py
> +        return False, error
❓ According to the docs for the actionlint script, it downloads the binary to the current path, or if you provide it a path in an argument. I don't see that supplied here, so how does actionlint end up into the system path? https://github.com/rhysd/actionlint/blob/v1.7.6/docs/install.md#download-script
> This script downloads actionlint (or actionlint.exe on Windows) binary to the current working directory. When you need to put the downloaded binary to some other directory, please give the directory path to the 2nd command line argument. The following example installs the latest version to /usr/bin.

2025-01-13 16:50 UTC, mimartin12 commented on src/bitwarden_workflow_linter/rules/run_actionlint.py
> +    version = "1.6.17"
I am not sure on renovate, since this might require a custom handler for renovate. However, moving this version into something like https://github.com/bitwarden/workflow-linter/blob/main/src/bitwarden_workflow_linter/default_settings.yaml would make it much easier to maintain.

2025-01-13 17:49 UTC, AmyLGalles commented on src/bitwarden_workflow_linter/rules/run_actionlint.py
> +        return False, error
If actionlint has to be installed from source, it uses the current directory  on line 88

2025-01-13 17:57 UTC, AmyLGalles commented on src/bitwarden_workflow_linter/rules/run_actionlint.py
> +    version = "1.6.17"
@michalchecinski I don't know how renovate works outside of package and action management. @mimartin12 I'd love to have it in a more centralized place where we can track versions but I don't feel like it fits in with settings or package versions. Do you have a suggestion?

2025-01-13 19:46 UTC, mimartin12 commented on src/bitwarden_workflow_linter/rules/run_actionlint.py
> +    version = "1.6.17"
Looking at the code right now, settings was the only place that stood out. If there is no way to set settings for each rule, then that sounds like a feature to me and is outside of scope IMO.

2025-01-13 19:57 UTC, mimartin12 commented on src/bitwarden_workflow_linter/rules/run_actionlint.py
> +        return False, error
Ah, I see that now. Thanks :) LGTM

2025-01-13 23:29 UTC, AmyLGalles commented on src/bitwarden_workflow_linter/rules/run_actionlint.py
> +    version = "1.6.17"
I think it's definitely possible to add actionlint version to the settings file, but I think creating that access is out of scope unless someone with more knowledge wanted to take it on.

2025-01-14 12:15 UTC, michalchecinski approved these changes

2025-01-14 15:07 UTC, mimartin12 approved these changes

2025-01-14 18:54 UTC, merged