[BRE-53] publishing workflow
bitwarden/workflow-linter pull request #4
Opened 2024-06-19 14:57 UTC by michalchecinski

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/BRE-53

## 📔 Objective

Add cd workflow to publish to pypi.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-20 15:35 UTC, mimartin12 requested changes

2024-06-20 15:35 UTC, mimartin12 commented on .github/workflows/cd.yml
> +        run: hatch bump ${{ needs.version-type.outputs.type }}
⚠️ This looks like it's calling the incorrect output, by the looks of `_version_type`.
```yaml
on:
  workflow_call:
    outputs:
      version:
        description: "version to be built"
        value: ${{ jobs.version.outputs.bump_type }}
```

it should be:
```suggestion
        run: hatch bump ${{ needs.version-type.outputs.version }}
```

2024-06-20 15:35 UTC, mimartin12 commented on .github/workflows/cd.yml
> +      - name: Login to Azure
⛏️  Consistent with other uses from above.
```suggestion
      - name: Login to Azure - CI Subscription
```

2024-06-20 15:35 UTC, mimartin12 commented on .github/workflows/enforce-labels.yml
> +    runs-on: ubuntu-latest
```suggestion
    runs-on: ubuntu-22.04
```
❓  Should this be pinned?

2024-06-21 08:37 UTC, michalchecinski commented on .github/workflows/enforce-labels.yml
> +    runs-on: ubuntu-latest
It should. Thanks!

2024-06-21 14:07 UTC, mimartin12 approved these changes

2024-06-24 14:28 UTC, mimartin12 approved these changes

2024-06-25 14:10 UTC, mimartin12 approved these changes

2024-06-26 12:06 UTC, merged